#+title: Лабораторная работа 2
#+LANGUAGE: ru
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [a4paper,fleqn,12pt]
#+options: toc:nil title:nil
#+property: header-args :noweb yes :eval no-export
#+property: header-args:julia :exports none
#+LATEX_HEADER: \usepackage[lmargin=15mm, rmargin=15mm, tmargin=2cm, bmargin=2cm]{geometry}
#+LATEX_HEADER: \usepackage{mathtools}
#+LATEX_HEADER: \DeclarePairedDelimiter{\lint}{(}{]}

\begin{titlepage}
  \Large
  \begin{center}
    Санкт-Петербургский\\
    Политехнический университет Петра Великого\\
    \vspace{10em}
    Математическая статистика\\
    \vspace{2em}
    \textbf{Отчёт по лабораторным работам 5-8}
  \end{center}
  \vspace{6em}
  \begin{flushright}
    Студент: Копнов Александр Александрович\\
    Преподаватель: Баженов Александр Николаевич\\
    Группа: 5030102/00101
  \end{flushright}
  \vspace{\fill}
  \begin{center}
    Санкт-Петербург\\
    2023
  \end{center}
\end{titlepage}
\tableofcontents
\listoffigures
\listoftables

* Постановка задачи
1. Сгенерировать двумерные выборки размерами 20, 60, 100 для нормального
   двумерного распределения \(N(x,y,0,0,1,1,\rho)\). Коэфициент корреляции \(\rho\)
   взять равным 0, 0.5, 0.9. Каждая выборка генерируется 1000 раз и для неё
   вычисляются: среднее значение, среднее значение квадрата и дисперсия
   коэффициентов корреляции Пирсона, Спирмена и квадрантного коэффициента
   корреляции. Повторить все вычисления для смеси нормальных распределений:
   \begin{equation}
   \label{eq:1}
   f(x,y) = 0.9N(x,y,0,0,1,1,0.9) + 0.1N(x,y,0,0,10,10,-0.9)
 \end{equation}
   Изобразить сгенерированные точки на плоскости и нарисовать эллипс равновероятности.
2. Найти отрезки коэффициентов линейной регрессии \(y_i=a + b x_i + e_i\)
   используя 20 точек на отрезке \([-1.8;2]\) с равномерным шагом равным 0.2.
   Ошибку \(e_i\) считать нормально распределённой с параметрами \((0,1)\). В
   качестве эталонной зависимости взять \(y_i = 2 + 2x_i + e_i\). При построении
   оценок коэффициентов использовать два критерия: критерий наименьших квадратов
   и критерий наименьших модулей. Проделать то же самое для выборки, у которой в
   значения \(y_1\) и \(y_{20}\) вносятся возмущения 10 и -10
3. Сгенерировать выборку объёмом 1000 элементов для нормального распределения
   \(N(x,0,1)\). По сгенерированной выборке оценить параметры \(\mu\) и \(\sigma\)
   нормального закона методом максимального правдоподобия. В качестве
   основной гипотезы \(H_0\) будем считать, что сгенерированной
   распределение имеет вид \(N(x,\hat{\mu},\hat{\sigma})\). Проверить основную
   гипотезу, используя критерий согласия \(\chi^{2}\). В качестве уровня
   значимости взять \(\alpha = 0.05\). Привести таблицу вычислений \(\chi^2\).\\
   Исследовать точность (чувствительность) критерия \(\chi^2\) --- сгенерировать
   выборки равномерного распределения и распределения Лапласа малого объёма
   (например 20 элементов). Проверить их на нормальность.
4. Для двух выборок размерами 20 и 100 элементов, сгенерированных согласно
   нормальному закону \(N(x,0,1)\), для параметров положения и масштаба
   построить асимптотически нормальные интервальные оценки на основе
   точечных оценок метода максимального правдоподобия и классические
   интервальные оценки на основе статистик \(\chi^2\) и Стьюдента. В качестве
   параметра надёжности взять \(\gamma = 0.95\).

* Теория

** Двумерное нормальное распределение

Двумерная случайная величина \(X,Y\) называется распределённой нормально (или
просто нормальной), если её плотность вероятности определена формулой
\begin{equation}
\label{eq:2}
N(x,y,\overline{x},\overline{y},\sigma_{x},\sigma_{y},\rho) = \frac{1}{2\pi\sigma_{x}\sigma_{y}\sqrt{1 - \rho^2}} \times \exp \left\{ - \frac{1}{2(1-\rho^2)}
\left[ \frac{(x - \overline{x})^2}{\sigma_{x}^2} - 2\rho \frac{(x-\overline{x})(y-\overline{y})}{\sigma_{x}\sigma_{y}} +
\frac{(y-\overline{y})^2}{\sigma_{y}^2} \right] \right\}
\end{equation}

Компоненты \(X,Y\) двумерной нормальной с.в. также распределены нормально с
математическими ожиданиями \(\overline{x},\overline{y}\) и средними
квадратическими отклонениями \(\sigma_{x},\sigma_{y}\) соответственно [1, с. 133-134]. Параметр \rho называется
коэффициентом корреляции

** Корреляционный момент (ковариация) и коэффициент корреляции

Корееляционным моментом, иначе ковариацией, двух случайных величин \(X\) и \(Y\)
называется математическое ожидание произведения отклонений этих случайных
величин от их математических ожиданий [1, с. 141].
\begin{equation}
\label{eq:3}
K = cov(X,Y) = M[(X - \overline{x})(Y - \overline{y})]
\end{equation}

Коэффициентом корреляции \rho двух случайных величин \(X\) и \(Y\) называется
отношение их корреляционного момента к произведению их средних квадратических
отклонений:
\begin{equation}
\label{eq:4}
\rho = \frac{K}{\sigma_{x}\sigma_{y}}
\end{equation}

Коэффициент корреляции --- это нормированная числовая характеристика, являющаяся
мерой близости зависимости между случайными величинами к линейной [1, с. 150].
** Выборочные коэффициенты корреляции
*** Выборочный коэффициент корреляции Пирсона

Пусть по выборке значений \({x_i,y_i}_{1}^{n}\) двумерной с.в. \((X,Y)\) требуется
оценить коэффициент корреляции \(\rho = \frac{cov(X,Y)}{\sqrt{DX DY}}\).
Естественной оценкой для \rho служит его статистический аналог в виде выборочного
коэффициента корреляии, предложенного К.Пирсоном, ---
\begin{equation}
\label{eq:5}
r = \frac{\frac{1}{n}\sum (x_i - \overline{x})(y_i - \overline{y})}{\sqrt{\frac{1}{n} \sum (x_i - \overline{x})^2 \frac{1}{n} \sum (y_i - \overline{y})^2}} =
\frac{K}{s_{X}s_{Y}}
\end{equation}
где \(K,s_{X}^2,s_{Y}^2\) --- выборочные ковариация и дисперсии с.в. \(X\) и \(Y\) [1,
с. 535]
*** Выборочный квадрантный коэффициент корреляции

Кроме выборочного коэффициента корреляции Пирсона, существуют и другие оценки
степени взаимосвязи между случайными величинами. К ним относится выборочный
квадрантный коэффициент корреляии
\begin{equation}
\label{eq:6}
r_{Q} = \frac{(n_1 + n_3) - (n_2 + n_4)}{n}
\end{equation}

где \(n_1,n_2,n_3,n_4\) --- количества точек с координатами \(x_i,y_i\),
попавшими соответствено в I, I​I, I​I​I, I​V квадранты декартовой системы с осями \(x'
= x - med x, y' = y - med y\) и с центром в точке с координатами \((med x, med y)\)
*** Выборочный коэфффициент ранговой корреляции Спирмена

На практике нередко требуется оценить степень взаимодействия между
качественными признаками изучаемого объекта. Качественным называется признак,
который нельзя измерить точно, но который позволяет сравнивать изучаемые объекты
между собой и располагать их в порядке убывания или возрастания их качества. Для
этого объекты выстраиваются в определённом порядке в соответствии с
рассматриваемым признаком. Процесс упорядочения называется ранжированием, и
каждому члену упорядоченной последовательности объектов присваивается ранг, или
порядковый номер. Например, объекту  с наименьшим значением признака
присваивается ранг 1, следующему за ним объекту --- ранг 2, и т.д. Таким
образом, происходит сравнение каждого объекта со всеми объектами изучаемой
выборки.

Если объект обладает не одним, а двумя качественными признаками --- переменными
\(X\) и \(Y\), то для исследования их взаимосвязи используют выборочный
коэффициент корреляции между двумя последовательностями рангов этих признаков.
Обозначим ранги, соответствующие значениям переменной \(X\), через \(u\), а
ранги, соответствующие значениям переменной \(Y\) --- через \(v\).

Выборочный коэффициент ранговой корреляции Спирмена определяется как выборочный
коэффициент корреляции Пирсона между рангами \(u,v\) переменных \(X,Y\):
\begin{equation}
\label{eq:7}
r_{S} = \frac{\frac{1}{n}\sum (u_i - \overline{u})(v_i - \overline{v})}{\sqrt{\frac{1}{n} \sum (u_i - \overline{u})^2 \frac{1}{n} \sum (v_i - \overline{v})^2}},
\end{equation}
где \(\overline{u} = \overline{v} = \frac{1 + 2 + \ldots + n}{n} = \frac{n+1}{2}\)
--- среднее значение рангов [1, с. 540-541]
** Эллипсы рассеивания
Рассмотрим поверхность распределения, изображающую функцию \eqref{eq:1}. Она имеет вид
холма, вершина которого находится над точкой \((\overline{x},\overline{y})\).\\
В сечении поверхности распределения плоскостями, параллельными оси
\(N(x,y,\overline{x},\overline{y},\sigma_{x},\sigma_{y},\rho)\), получаются кривые, подобные
нормальным кривым распределения. В сечении поверхности распределения
плоскостями, параллельными плоскости \(xOy\):
\begin{equation}
\label{eq:8}
\frac{(x - \overline{x})^2}{\sigma_{x}^2} - 2\rho \frac{(x-\overline{x})(y-\overline{y})}{\sigma_{x}\sigma_{y}} + \frac{(y-\overline{y})^2}{\sigma_{y}^2} = const
\end{equation}

Уравнение эллипса \eqref{eq:8} можно проанализировать обычными методами аналитической
геометрии. Применяя их, убеждаемся, что центр эллипса 8 находится в точке с
координатами \((\overline{x},\overline{y})\); что касается направления осей
симметрии эллипса, они составляют с осью \(Ox\) углы, определяемые уравнением
\begin{equation}
\label{eq:9}
\tan(2\alpha) = \frac{2\rho\sigma_{x}\sigma_{y}}{\sigma_{x}^2 - \sigma_{y}^2}
\end{equation}
Это уравнение даёт два значения углов: \(\alpha\) и \(\alpha_{1}\), различающиеся на
\(\frac{\pi}{2}\).

Таким образом, ориентация эллипса \eqref{eq:8} относительно координатных осей
находится в прямой зависимости от коэффициента корреляции \(\rho\) системы
\((X,Y)\); если величины не коррелированны, то оси симметрии эллипса параллельны
координатным осям; в противном случае они составляют с координатными осями
некоторый угол.

Пересекая поверхность распределения плоскостями, параллельными плоскости
\(xOy\), и проектируя сечения на плоскость \(xOy\) мы получим целое семейство
подобных и одинаково расположенных эллипсов с общим центром
\((\overline{x},\overline{y})\). Во всех точках каждого из таких эллипсов
плотность распределения \(N(x,y,\overline{x},\overline{y},\sigma_{x},\sigma_{y},\rho)\) постоянна.
Поэтому такие эллипсы называются эллипсами равной плотности или эллипсами
рассеивания. Общие оси всех эллипсов рассеивания называются главными осями
рассеивания [2, с. 193-194]

** Простая линейная регрессия

*** Модель простой линейной регрессии

Регрессионную модель описания данных называют простой линейной регрессией, если
\begin{equation}
\label{eq:10}
y_i = \beta_{0} + \beta_{1}x_i + \epsilon_{i}, i = \overline{1,n}
\end{equation}
где \(x_1,\ldots,x_n\) --- заданные числа (значения фактора); \(y_1,\ldots,y_n\) ---
наблюдаемые значения отклика; \(\epsilon_{1},\ldots,\epsilon_{n}\) --- независимые, нормально
распределённые \(N(0,\sigma)\) с нулевым мат. ожиданием и одинаковой (неизвестной)
дисперсией случайные величины (ненаблюдаемые); \(\beta_{0},\beta_{1}\) --- неизвестные
параметры, подлежащие оцениванию

В модели \eqref{eq:10} отклик \(y\) зависит от одного фактора \(x\) и весь
разброс экспериментальных точек объясняется только погрешностями наблюдений
(результатов измерений) отклика \(y\). Погрешности результатов измерений \(x\) в
этой модели полагают существенно меньшими погрешностей результатов измерений
\(y\) , так что ими можно пренебречь [1, с.507].
*** Метод наименьших квадратов

При оценивании параметров регрессионной модели используют различные методы. Один
из наиболее распространённых подходов заключается в следующем: вводится мера
(критерий) рассогласования отклика и регрессионной функции, и оценки параметров
регрессии определяются так, чтобы сделать это рассогласование наименьшим.
Достаточно простые расчётные формулы для оценок получают при выборе критерия в
виде суммы квадратов отклонений значений отклика от значений регрессионной
функции (сумма квадратов остатков):
\begin{equation}
\label{eq:11}
Q(\beta_{0},\beta_{1}) = \sum_{i=1}^n \epsilon_{1}^{2} = \sum_{i=1}^n (y_i - \beta_{0} - \beta_{1}x_i)^2 \to \min_{\beta_{0},\beta_{1}}
\end{equation}

Задача минимизации квадратичного критерия \(Q(\beta_{0},\beta_{1})\) носит название задачи
метода наименьших квадратов (МНК), а оценки \(\hat{\beta_{0}},\hat{\beta_{1}}\) параметров
\(\beta_{0},\beta_{1}\), реализующие минимум критерия \(Q(\beta_{0},\beta_{1})\), называют МНК-оценками [1,
с. 508].
*** Расчётные формулы для МНК-оценок

МНК-оценки параметров \(\hat{\beta_{0}},\hat{\beta_{1}}\) находятся из условия обращения
функции \(Q(\beta_{0},\beta_{1})\) в минимум. Для нахождения МНК-оценок \(\hat{\beta_{0}},\hat{\beta_{1}}\)
выпишем необходимые условия экстремума
\begin{equation}
\label{eq:12}
\begin{cases}
  \pdv{Q}{\beta_{0}} = -2 \sum_{i=1}^n (y_i - \beta_{0} - \beta_{1}x_i) = 0\\
  \pdv{Q}{\beta_{1}} = -2 \sum_{i=1}^n (y_i - \beta_{0} - \beta_{1}x_i)x_i = 0
\end{cases}
\end{equation}

Далее для упрощения записи сумм будем опускать индекс суммирования. Из системы
\eqref{eq:12} получим:
\begin{equation}
\label{eq:13}
\begin{cases}
  n\hat{\beta_{0}} + \hat{\beta_{1}} \sum x_i = \sum y_i\\
  \hat{\beta_{0}}\sum x_i + \hat{\beta_{1}}\sum x_i^2 = \sum x_i y_i
\end{cases}
\end{equation}

Разделим оба уравнения на n:
\begin{equation}
\label{eq:14}
\begin{cases}
  \hat{\beta_{0}} + \hat{\beta_{1}} \frac{1}{n}\sum x_i = \frac{1}{n}\sum y_i\\
  \hat{\beta_{0}}\frac{1}{n}\sum x_i + \hat{\beta_{1}}\frac{1}{n}\sum x_i^2 = \frac{1}{n}\sum x_i y_i
\end{cases}
\end{equation}
и, используя известные статистические обозначения для выборочных первых и вторых
начальных моментов
\begin{equation}
\label{eq:15}
\overline{x} = \frac{1}{n}\sum x_i,\overline{y} = \frac{1}{n}\sum y_i, \overline{x^2} = \frac{1}{n}\sum x_i^2, \overline{xy} = \frac{1}{n}\sum x_i y_i
\end{equation}

получим
\begin{equation}
\label{eq:16}
\hat{\beta_{0}} + \hat{\beta_{1}}\overline{x} = \overline{y}\\
\hat{\beta_{0}}\overline{x} + \hat{\beta_{1}}\overline{x^2} = \overline{xy}
\end{equation}
откуда МНК-оценку \(\hat{\beta_{1}}\) наклона прямой регрессии находим по формуле
Крамера
\begin{equation}
\label{eq:17}
\hat{\beta_{1}} = \frac{\overline{xy} - \overline{x} \cdot \overline{y}}{\overline{x^2} - (\overline{x})^2}
\end{equation}
а МНК-оценку \(\hat{\beta_{0}}\) определяем непосредственно из первого уравнения
системы \eqref{eq:16}:
\begin{equation}
\label{eq:18}
\hat{\beta_{0}} = \overline{y} - \overline{x}\hat{\beta_{1}}
\end{equation}

Заметим, что определитель системы \eqref{eq:16}:
\begin{equation}
\label{eq:19}
\overline{x^2} - (\overline{x})^2 = \frac{1}{n} \sum (x_i - \overline{x})^2 = s_{x}^2 > 0
\end{equation}

если среди значений \(x_1,\ldots,x_n\) есть различные, что и будем предполагать.

Доказательство минимальности функции \(Q(\beta_{0},\beta_{1})\) в стационарной точке проведём
с помощью известного достаточного признака экстремума функции двух переменных.
Имеем:
\begin{equation}
\label{eq:20}
\pdv[2]{Q}{\beta_{0}} = 2n, \pdv[2]{Q}{\beta_{1}} = 2 \sum x_i^2 = 2n\overline{x^2}, \frac{\partial^2 Q}{\partial \beta_{1}\partial\beta_{0}} = 2 \sum x_i = 2n\overline{x}
\end{equation}
\begin{equation}
\label{eq:21}
\Delta = \pdv[2]{Q}{\beta_{0}}\cdot\pdv[2]{Q}{\beta_{1}} - \left( \frac{\partial^2 Q}{\partial \beta_{1}\partial\beta_{0}} \right) =
4n^2\overline{x^2} - 4n^2(\overline{x})^2 = 4n^2s_{x}^2 > 0
\end{equation}

Этот результат вместе с условием \(\pdv[2]{Q}{\beta_{0}^2} = 2n > 0\) означает, что в
стационарной точке функция \(Q\) имеет минимум [1,с. 508-511]

** Робастные оценки коэффициентов линейной регрессии

Робастность оценок коэффициентов линейной регрессии (т.е. их устойчивость по отношению к
наличию в данных редких, но больших по величине выбросов) может быть обеспечена различ-
ными способами. Одним из них является использование метода наименьших модулей вместо
метода наименьших квадратов:
\begin{equation}
\label{eq:22}
\sum_{i=1}^n \abs{ y_i - \beta_{0} - \beta_{1}x_i } \to \min _{\beta_{0},\beta_{1}}
\end{equation}

Напомним, что использование метода наименьших модулей в задаче оценивания параметра
сдвига распределений приводит к оценке в виде выборочной медианы, обладающей робастными
свойствами. В отличие от этого случая и от задач метода наименьших квадратов, на практике
задача \eqref{eq:22} решается численно. Соответствующие процедуры представлены в некоторых совре-
менных пакетах программ по статистическому анализу.
Здесь мы рассмотрим простейшую в вычистлительном отношении робастную альтернативу
оценкам коэффициентов линейной регрессии по МНК. Для этого сначала запишем выражения
для оценок \eqref{eq:18} и \eqref{eq:17} в другом виде:
\begin{equation}
\label{eq:23}
\begin{cases}
  \hat{\beta_{1}} =\frac{\overline{xy} - \overline{x}\cdot \overline{y}}{\overline{x^2} - (\overline{x})^2} =
  \frac{k_{xy}}{s_{x}^2} = \frac{k_{xy}}{s_{x}s_{y}} \cdot \frac{s_{y}}{s_{x}} = r_{xy} \frac{s_{y}}{s_{x}}\\
  \hat{\beta_{0}} = \overline{y} - \overline{x}\hat{\beta_{1}}
\end{cases}
\end{equation}
В формулах \eqref{eq:23} заменим выборочные средние \(\overline{x}\),
\(\overline{y}\) соответственно на робастные выборочные медианы \(med x\) и
\(med y\), среднеквадратические отклонения \(s_{x},s_{y}\) на робастные нормированные
интерквартильные широты \(q_{x}^{*},q_{y}^{*}\), выборочный коэффициент корреляции
\(r_{xy}\) на знаковый коэффициент корреляции \(r_{Q}\):
\begin{equation}
\label{eq:24}
\hat{\beta_{1}}_{R} = r_{Q} \frac{q_{y}^{*}}{q_{x}^{*}}
\end{equation}
\begin{equation}
\label{eq:25}
\hat{\beta_{0}}_{R} = med y - \hat{\beta_{1}}_{R} med x
\end{equation}
\begin{equation}
\label{eq:26}
r_{Q} = \frac{1}{n} \sum_{i=1}^n sgn(x_i - med x) sng(y_i - med y)
\end{equation}
\begin{equation}
\label{eq:27}
q_{y}^{*} = \frac{y_{(j)} - y_{(l)}}{k_{q}(n)}, \quad q_{x}^{*} = \frac{x_{(j)} - x_{(l)}}{k_{q}(n)},
\begin{cases}
  \left[ \frac{n}{4} + 1 \right] \text{ при } \frac{n}{4} \text{ дробном},\\
  \frac{n}{4} \text{ при } \frac{n}{4} \text{ целом}
\end{cases}
j = n - l + 1
\end{equation}

Уравнение регрессии здесь имеет вид
\begin{equation}
\label{eq:28}
y = \hat{\beta_{0}}_{R} + \hat{\beta_{1}}_{R}x
\end{equation}

Статистики выборочной медианы и интерквартильной широты обладают робастными
свойствами в силу того, что основаны на центральных порядковых статистиках,
малочувствительных к большим по величине выбросам в данных. Статистика
выборочного знакового коэффициента робастна, так как знаковая функция \(sgn z\)
чувствительна не к величине аргумента, а только к его знаку. Отсюда оценка
прямой регрессии обладает очевидными робастными свойствами устойчивости к
выбросам по координате \(y\), но она довольно груба [1, с. 518-519].
** Метод максимального правдоподобия
Одним из универсальных методов оценивания является метод максимального
правдоподобия, предложенный Р.Фишером (1921). Пусть \(x_1,\ldots,x_n\) --- случайная
выборка из генеральной совокупности с плотностью вероятности \(f(x,\theta);
L(x_1,\ldots,x_n,\theta)\) --- функция правдоподобия (ФП), представляющая собой совместную
плотность вероятности независимых с.в. \(x_1,\ldots,x_n\) и рассматриваемая как
функция неизвестного параметра \(\theta\):
\begin{equation}
\label{eq:29}
L(x_1,\ldots,x_n,\theta) = f(x_1,\theta)f(x_2,\theta)\ldots f(x_n,\theta)
\end{equation}

*Определение* Оценкой максимального правдоподобия (о.м.п.) будем называть такое значение
\(\hat{\theta}\) из множества допустимых значений параметра \theta, для которого ФП
принимает наибольшее значение при заданных \(x_1,\ldots,x_n\):
\begin{equation}
\label{eq:30}
\hat{\theta} = \arg \max_{\theta} L(x_1,\ldots,x_n,\theta)
\end{equation}
Если ФП дважды дифференцируема, то её стационарные значения даются корнями
уравнения
\begin{equation}
\label{eq:31}
\pdv{L(x_1),\ldots,x_n,\theta}{\theta} = 0
\end{equation}

Достаточным условием того, чтобы некоторое стационарное значение \(\tilde{\theta}\) было
локальным максимумом является неравенство
\begin{equation}
\label{eq:32}
\pdv[2]{L}{\theta}(x_1,\ldots,x_n,\tilde{\theta}) < 0
\end{equation}

Определив точки локальных максимумов ФП (если их несколько), находят наибольший,
который и даёт решение задачи \eqref{eq:29}. Часто проще искать максимум
логарифма ФП, так как он имеет максимум в одной точке с ФП:
\begin{equation}
\label{eq:33}
\pdv{\ln L}{\theta} = \frac{1}{L}\pdv{L}{\theta}, L > 0
\end{equation}
и соответственно решать уравнение
\begin{equation}
\label{eq:34}
\pdv{\ln L}{\theta} = 0
\end{equation}
которое называют /уравнением правдоподобия/. В задаче оценивания векторного
параметра \(\theta = (\theta_{1},\ldots,\theta_{m})\) аналогично \eqref{eq:30} находится максимум ФП
нескольких аргументов:
\begin{equation}
\label{eq:35}
\hat{\theta} = \arg \max_{\theta_{1},\ldots,\Theta_{m}} L(x_1,\ldots,x_n,\theta_{1},\ldots,\theta_{n})
\end{equation}
и в случае дифференцируемости ФП выписывается система уравнений правдоподобия
\begin{equation}
\label{eq:36}
\pdv{L}{\theta_{k}} = 0 \text{ или } \pdv{\ln L}{\theta_{k}} = 0, k = \overline{1,m}
\end{equation}
** Проверка гипотезы о законе распределения генеральной совокупности. Метод хи-квадрат

Исчерпывающей характеристикой изучаемой случайной величины является её закон
распределения. Поэтому естественно стремление исследователей построить этот
закон приближённо на основе статистических данных.

Сначала выдвигается гипотеза о виде закона распределения

После того как выбран вид закона,, возникает задача оценивания его параметров и
проверки (тестирования) закона в целом.

Для проверки гипотезы о законе распределения применяются критерии согласия.
Таких критериев существует много. Мы рассмотрим наиболее обоснованный и наиболее
часто использумый на практике --- критерий \(\chi^2\), введённый К.Пирсоном (1900
г.) для случая, когда параметры распределения известны. Этот критерий был
существенно уточнён Р. Фишером (1924 г.), когда параметры распределения
оцениваются по выборке, используемой для проверки.

Мы ограничимся рассмотрением случая одномерного распределения.

Итак, выдвинута гипотеза \(H_{0}\) о генерально законе распределения с функцией
распределения \(F(x)\)

Рассматриваем случай, когда гипотетическая функция распределения \(F(x)\) не
содержит неизвестных параметров.

Разобьём генеральную совокупность, т.е. множество значений изучаемой случайной
величины \(X\) на \(k\) непересекающихся подмножеств \(\Delta_{1},\ldots,\Delta_{k}\).

Пусть \(p_i = P(X \in \Delta_{i}), i = \overline{1,k}\).

Если генеральная совокупность --- вся вещественная ось, то подмножества \(\Delta_{i} =
\lint{a_{i-1},a_{i}}\) --- полуоткрытые промежутки (\(i = \overline{2,k-1}\)). Крайние
промежутки будут полубесконечными: \(\Delta_{1} = \lint{-\infty,a_1},\Delta_{k} = \lint(a_{k-1},+\infty)\). В
этом случае \(p_i = F(a_i) - F(a_{i-1}); a_0 = -\infty, a_k = + \infty (i=\overline{1,k})\)

Отметим, что \(\sum_{i=1}^k p_i = 1\). Будем предполагать, что все \(p_i > 0,
i=\overline{1,k}\).

Пусть, далее, \(n_1,\ldots,n_k\) --- частоты попадания выборочных элементов в
подмножества \(\Delta_{1},\ldots,\Delta_{k}\) соответственно.

В случае справедливости гипотезы \(H_0\) относительные частоты \(n_i / n\) при
большом \(n\) должны быть близки к вероятностям \(p_i\), поэтому за меру
отклонения выборочного распределения от гипотетического с функцией \(F(x)\)
естественно выбрать величину
\begin{equation}
\label{eq:37}
Z = \sum_{i=1}^k c_i \left( \frac{n_i}{n} - p_i \right)^2
\end{equation}
где \(c_i\) --- веса. К.Пирсоном в качестве весов выбраны числа \(c_i =
\frac{n}{p_i}\). Тогда получается статистика критерия хи-квадрат К.Пирсона
\begin{equation}
\label{eq:38}
\chi^2 = \sum_{i=1}^k \frac{n}{p_i} \left( \frac{n_i}{n} - p_i \right)^2 = \sum_{i=1}^k \frac{(n_i - n p_i)^2}{n p_i}
\end{equation}
которая обозначена тем же символом, что и закон распределения хи-квадрат.

К.Пирсоном доказана теорема об асимптотическом поведении статистики \(\chi^2\),
указывающая путь её применения\\
*Теорема К.Пирсона*. Статистика критерия \(\chi^2\) асимптотически распределена по
закону \(\chi^2\) с \(k-1\) степенями свободы.

Это означает, что независимо от вида проверяемого распределения, т.е. функции
\(F(x)\), выборочная функция распределения статистики \(\chi^2\)при \(n \to \infty\)
стремится к функции распределения случайной величины с плотностью вероятности
\begin{equation}
\label{eq:39}
f_{k-1}(x) =
\begin{cases}
  0, x \leq 0\\
  \frac{1}{2^{\frac{k-1}{2}}\Gamma(\frac{k-1}{2})} x^{\frac{k-3}{2}}e^{-\frac{x}{2}}, x > 0
\end{cases}
\end{equation}
Для прояснения сущности метода \(\chi^2\) сделаем ряд замечаний.

*Замечание 1*. Выбор подмножеств \(\Delta_{1},\ldots,\Delta_{k}\) и  их числа k в принципе ничем не
 регламентируется, так как \(n \to \infty\). Но так как число \(n\) хотя и очень
 большое, но конечное, то \(k\) должно быть с ним согласовано. Обычно его берут
 таким же, как и для построения гистограммы, т.е. можно руководствоваться
 формулой
 \begin{equation}
 \label{eq:40}
 k \approx 1.72\sqrt[3]{n}
 \end{equation}
 или формулой Старджесса
 \begin{equation}
 \label{eq:41}
 k \approx 1 + 3.3 \lg n
 \end{equation}
 При этом, если \(\Delta_{1},\ldots,\Delta_{n}\) --- промежутки, то их длины удобно сделать равными,
 за исключением крайних --- полубесконечных.

 *Замечание 2* (о числе степеней свободы). Числом степеней свободы функции (по
  старой терминологии) называется число её независимых аргументов. Аргументами
  статистики \(\chi^2\) являются частоты \(n_1,\ldots,n_k\). Эти частоты связаны одним
  равенством \(n_1 + n_2 + \dots + n_k = n\), а в остальном независимы в силу
  независимости элементов выборки. Таким образом, функция \(\chi^2\) имеет \(k-1\)
  независимых аргументов: число частот минус одна связь. В силу теоремы Пирсона
  число степеней свободы статистики \(\chi^2\) отражается на виде асимптотической
  плотности \(f_{k-1}(x)\)

  На основе общей схемы проверки статистических гипотез сформулируем следующее
  правило.\\
  *Правило проверки гипотезы о законе распределения по методу \(\chi^2\)*
  1. Выбираем уровень значимости \(\alpha\).
  2. По таблице [3, с. 358] находим квантиль \(\chi_{1-\alpha}^2(k-1)\) распределения
     хи-квадрат с \(k-1\) степенью свободы порядка \(1 - \alpha\)
  3. С помощью гипотетической функции распределения \(F(x)\) вычисляем
     вероятности \(p_i = P(X \in\Delta_{i}), i = \overline{1,k}\)
  4. Находим частоты \(n_i\) попадания элементов выборки в подмножества \(\Delta_{i},i = \overline{i,k}\).
  5. Вычисляем выборочное значение статистики критерия \(\chi^2\):
            \begin{equation}
     \label{eq:42}
     \chi_{B}^2 = \sum_{i=1}^k \frac{(n_i) - n p_i)^2}{n p_i}
     \end{equation}
  6. Сравниваем \(\chi^2_{B}\) и квантиль \(\chi_{1-\alpha}^2(k-1)\).
     a. Если \(\chi^2_{B} < \chi^2_{1-\alpha}(k-1)\), то гипотеза \(H_0\) на данном этапе
        проверки принимается.
     b. Если \(\chi^2_{B} \geq \chi^2_{1-\alpha}\), то гипотеза \(H_0\) отвергается, выбирается одно
        из альтернативных распределений, и процедура проверки повторяется

*Замечание 3*. Из формулы \eqref{eq:38} видим, что веса \(c_i = n / p_i\)
 пропорциональны \(n\), т.е. с ростом \(n\) увеличиваются. Отсюда следует, что
 если выдвинутая гипотеза неверна, то относительные частоты \(n_i / n\) не будут
 близки к вероятностям \(p_i\), и с ростом n величина \(\chi^2_{B}\) будет
 увеличивать- ся. При фиксированном уровне значимости \(\alpha\) будет фиксировано
 пороговое число - квантиль \(\chi^2_{1-\alpha}(k -1)\), поэтому, увеличивая \(n\), мы
 придём к неравенству \(\chi^2_{B} > \chi^2_{1-\alpha}(k-1)\), т.е. с увеличением объёма выборки
 неверная гипотеза будет отвергнута.

 *Замечание 4*. Теория и практика применения критерия \(\chi^2\) указывают, что если
  для каких-либо подмножеств \(\Delta_{i}(i=\overline{1,k})\) условие \(n p_i \geq 5\) не
  выполняется, то следует объединить соседние подмножества (промежутки)

  Это условие выдвигается требованием близости величин \(\frac{n_i - n
  p_i}{\sqrt{n p_i}}\), квадраты которых являются слагаемыми \(\chi^2\) к
  нормальным \(N(0,1)\). Тогда случайная величина в формуле \eqref{eq:38} будет
  распределена по закону, близкому к хи-квадрат. Такая близость обеспечивается
  достаточной численностью элементов в подмножествах \(\Delta_{i}\) [1, с. 481-485]


** Доверительные интервалы для параметров нормального распределения
